### ISSUE TITLE
Problem with a specific date

### ISSUE THREAD

**Issue by flopezag** [flopezag/fiware-sla#4]
The adjust_time_delta produce an exception with the date:

2018-03-31 07:59:09+01:00

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/fernandolopez/Documents/workspace/python/fiware-sla/SLAMeassurement.py", line 31, in <module>
    result = map(jira_instance.filter_issue, issues)
  File "/Users/fernandolopez/Documents/workspace/python/fiware-sla/core/jiraconnector.py", line 91, in filter_issue
    t_created, t_now).total_seconds()
  File "/Users/fernandolopez/Documents/workspace/python/fiware-sla/core/SLATime.py", line 99, in office_time_between
    a_delta = SLATime.adjust_time_delta(t=a, start=start, stop=stop)
  File "/Users/fernandolopez/Documents/workspace/python/fiware-sla/core/SLATime.py", line 45, in adjust_time_delta
    t = t.replace(day=t.day+(7-weekday), hour=start_hour, minute=0, second=0)
ValueError: day is out of range for month

**Comment by flopezag** [comment]
Resolved with the commit 4db3871fe1b7ff262cdd70a9ff4b654728fb8510
